kafka:
  bootstrap.servers: ${KAFI_KAFKA_SERVER}
  security.protocol: ssl
  ssl.keystore.location: ${KAFI_KAFKA_KEYSTORE_JKS_FILE}
  ssl.keystore.password: ${KAFI_KAFKA_KEYSTORE_PASSWORD}
  ssl.endpoint.identification.algorithm: https
  ssl.ca.location: ${KAFI_KAFKA_ROOT_CA_PEM_FILE}
  
schema_registry:
  schema.registry.url: ${KAFI_SCHEMA_REGISTRY_URL}
  basic.auth.credentials.source: USER_INFO
  basic.auth.user.info: ${KAFI_SCHEMA_REGISTRY_USER_INFO}

kafi:
  flush.timeout: -1.0
  produce.batch.size: 1000
  retention.ms: 604800000
  consume.timeout: 5.0
  consume.batch.size: 1000
  consumer.group.prefix: ""
  enable.auto.commit: false
  session.timeout.ms: 45000
  auto.offset.reset: earliest
  progress.num.messages: 1000
  key.type: str
  value.type: json
